### ISSUE TITLE
feat: Extra elipsis on proposal card author

### ISSUE THREAD

**Issue by steinerkelvin** [agicommies/community-proposals#12]
![image](https://github.com/agicommies/community-proposals/assets/2822370/8b71a44e-99f8-4323-a76e-1a93d9b9aa67)

It should not have the elipsis on the right, but show the full "short address".

**Comment by steinerkelvin** [comment]
Note: by "short address" I mean the pattern `12345678...12345678` computed from an address by the function small_address

**Comment by steinerkelvin** [comment]
This is still broken.

<img width="351" alt="image" src="https://github.com/agicommies/community-proposals/assets/2822370/64c37faa-67ba-4d54-b903-6dde489e090e">

Can't we just disable this truncating behaviour and wrap the address in some sort of code/pre tag?

**Comment by vinicius-sacramento** [comment]
I just tested my branch dev locally and nothing happened here, can you provide me more information about this bug?
Can we create new proposals just as a test in dev.community-proposals?

https://github.com/agicommies/community-proposals/assets/50849605/b5a1ef47-2316-4e32-b0b3-736d9118d129

I'm going to do some tests to check if it's possible to remove the truncate, but it should be working as it is now.

**Comment by steinerkelvin** [comment]
Yeah, the preview deployments are pointing to the testnet and it's empty now. I think I'll point to the mainnet while we don't put something in the testnet.

**Comment by vinicius-sacramento** [comment]
@steinerkelvin found out that it was a config on brave, using font-size large.
To fix it I take off the static width we had in this code and now is working even with this font-size large.

![Image](https://github.com/agicommies/community-proposals/assets/50849605/d316e4eb-9cd8-4c10-9374-b80705f3d8ad)

![Image](https://github.com/agicommies/community-proposals/assets/50849605/ff2367c4-c0ea-4832-af02-d446a48109ca)
