### ISSUE TITLE
Compute dates based on block

### ISSUE THREAD

**Issue by steinerkelvin** [agicommies/community-proposals#13]
![image](https://github.com/agicommies/community-proposals/assets/2822370/f60a75dc-db67-4d60-a8f1-0daf6dd82b7b)

But how?

We can probably just multiply by the average block time. We just need to make sure it's sufficiently close to the actual target block time of 8 seconds.

**Comment by rad2520** [comment]
think its fine to assume 8 second blocktime, so the date / hours left doesnt increase and confuse people. also chain has been hitting the target blocktime pretty reliably. should be sufficient to just display hours left till expiration

**Comment by EdSDR** [comment]
`  
async function getTimeRemaining(expirationBlock: number) {
    return (expirationBlock - blockNumber) * 8;
 }
`
