### ISSUE TITLE
Quorum missing on expanded view

### ISSUE THREAD

**Issue by EdSDR** [agicommies/community-proposals#14]
![Image](https://github.com/agicommies/community-proposals/assets/89485015/2a31e452-8912-44b4-92cc-e6bc536b7729)

**Comment by steinerkelvin** [comment]
> @rad2520:  lets get a progress bar for participation rate from 0 - 100% with line at at 50% threshold. could color the bar share of for/against green and red

Idk if we should do the for/against coloring in the quorum bar, tho. That info is extra clear in the other bars. I'd only do the tick in the middle indicating the threshold for resolution (50%).

**Comment by rad2520** [comment]
sure info is already clear, but think having it as visual component of the bar could be worth it. allows to have an immediate gauge of it just by looking at the bar itself without having to read the numbers. 

but insignificant either way, im down with both
